[default]
db_dir = "."
confirmations = 6
lwd_url = "http://localhost:9067"
poll_interval = 10
notify_host = "localhost"
fvk = "zxviews1qw73xgmkqqqqpqx3f2a93lddczpdk4kt58dh5nceks7l8jhw6zc30up6ph3etllafdp5f90st33sa6p27jmevdelhx6fpmhk698vyu7lfn0z6gpqr3nfedhec5k9x0w826fej59j84xqkndqe0ymety9sgc4ttfn82gheu988d9dr9n99zege9egzadkwf8eeur3xm5tajctx625ux67w0dlsl8hsa4l889js800jq6xvcnyp3v0tnh65cqwq6xfnk9cqczue24wyyskv63ke"
starting_height = 1915516

[debug]
address = "127.0.0.1"

[release]
address = "0.0.0.0"
